---
image: quay.io/ansible/molecule:3.0.8
services:
  - docker:dind

stages:
  - test

before_script:
  - docker -v
  - python3 -V
  - ansible --version
  - molecule --version

test:molecule:
  stage: test
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    ANSIBLE_FORCE_COLOR: 1
  script:
    - molecule test
