---
image: rsprta/molecule-runner
services:
  - docker:dind

stages:
  - test
  - release

before_script:
  - docker -v
  - python3 -V
  - ansible --version
  - molecule --version

test:molecule:
  stage: test
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    ANSIBLE_FORCE_COLOR: 1
  script:
    - molecule test --debug

release:galaxy:
  stage: release
  script:
    - ansible-galaxy role import --token $GALAXY_TOKEN $GITLAB_USER_LOGIN ansible-role-node_exporter
  only:
    - tags
