---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint
    rev: master
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible/ansible-lint
    rev: master
    hooks:
      - id: ansible-lint
