---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: "Include radek_sprta.node_exporter"
      ansible.builtin.include_role:
        name: "radek_sprta.node_exporter"
