---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ansible-role-node-exporter
    image: ${MOLECULE_IMAGE:-rsprta/alpine-ansible}
    command: ''
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
